#!/bin/bash

# CLEF - GCP Setup Script
# Automates GCP project configuration with OpenTofu
# Usage: ./setup_gcp.sh [dev|test|prod]

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored messages
print_info() {
    echo -e "${BLUE}ℹ ${NC}$1"
}

print_success() {
    echo -e "${GREEN}✓${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

# Check if environment parameter is provided
if [ -z "$1" ]; then
    print_error "Environment parameter required"
    echo "Usage: $0 [dev|test|prod]"
    exit 1
fi

ENV=$1
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TERRAFORM_DIR="$SCRIPT_DIR/../terraform"
CREDS_DIR="$HOME/.cred/CLEF"

# Validate environment
case $ENV in
    dev|test|prod) ;;
    *)
        print_error "Invalid environment: $ENV"
        echo "Valid options: dev, test, prod"
        exit 1
        ;;
esac

print_info "Setting up GCP for environment: $ENV"
echo ""

# Check if OpenTofu is installed
if ! command -v tofu &> /dev/null; then
    print_error "OpenTofu not found. Please install it:"
    echo "  brew install opentofu"
    echo "  OR: https://opentofu.org/docs/intro/install/"
    exit 1
fi

print_success "OpenTofu found"

# Check if gcloud is authenticated (needed for Terraform Google provider)
if ! gcloud auth application-default print-access-token &> /dev/null; then
    print_warning "Not authenticated to GCP"
    print_info "Running: gcloud auth application-default login"
    gcloud auth application-default login
fi

print_success "GCP authentication verified"

# Create credentials directory
mkdir -p "$CREDS_DIR"
chmod 700 "$CREDS_DIR"

# Initialize Terraform
print_info "Initializing OpenTofu..."
cd "$TERRAFORM_DIR"
tofu init -upgrade

# Plan
print_info "Planning infrastructure for $ENV..."
tofu plan -var-file="environments/$ENV.tfvars" -out="tfplan-$ENV"

# Confirm
read -p "Apply this plan? (yes/no): " confirm
if [ "$confirm" != "yes" ]; then
    print_warning "Aborted"
    exit 0
fi

# Apply
print_info "Applying infrastructure..."
tofu apply "tfplan-$ENV"

# Extract service account key
print_info "Extracting service account key..."
KEY_FILE="$CREDS_DIR/clef-backend-${ENV}-key.json"
tofu output -raw service_account_key > "$KEY_FILE"
chmod 600 "$KEY_FILE"
print_success "Key saved to: $KEY_FILE"

# Generate .env file
print_info "Generating .env.$ENV..."
cat > "$SCRIPT_DIR/../.env.$ENV" << EOF
# Generated by setup_gcp.sh on $(date)
ENVIRONMENT=$ENV
PROJECT_ID=$(tofu output -raw project_id)

# Service Account
GOOGLE_APPLICATION_CREDENTIALS=$KEY_FILE

# Memorystore Redis
REDIS_HOST=$(tofu output -raw memorystore_host)
REDIS_PORT=$(tofu output -raw memorystore_port)
REDIS_URL=redis://$(tofu output -raw memorystore_host):$(tofu output -raw memorystore_port)/0

# Google OAuth (to be filled manually)
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GOOGLE_REDIRECT_URI=http://localhost:8000/auth/callback

# Application
USE_MOCKS=false
CORS_ORIGINS=http://localhost:4200,http://localhost:4202,http://localhost:8000

# Session
SESSION_SECRET_KEY=$(openssl rand -hex 32)

# QR Code
QR_CODE_SALT=$(openssl rand -hex 16)
EOF

print_success ".env.$ENV generated"

# Summary
echo ""
print_success "========================================="
print_success "GCP Setup Complete for $ENV!"
print_success "========================================="
echo ""
echo "Service Account: $(tofu output -raw service_account_email)"
echo "Key File: $KEY_FILE"
echo "Memorystore: $(tofu output -raw memorystore_host):$(tofu output -raw memorystore_port)"
echo ""
print_info "Next steps:"
echo "  1. Copy .env.$ENV to backend/.env"
echo "  2. Add GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET"
echo "  3. Share Google Sheets with the service account"
